name: Publish to Test PyPI

on:
  push:
    tags:
      - 'test-v*'
    branches:
      - 'dev'

jobs:
  deploy_testpypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for full commit history check
    - name: Verify tag is on dev branch
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        COMMIT=$(git rev-parse $TAG_NAME)
        if ! git branch --contains $COMMIT | grep -qw dev; then
          echo "::error::Tag $TAG_NAME must be created from dev branch"
          exit 1
        fi
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        echo "TWINE_USERNAME  is set to $TWINE_USERNAME"
        echo "TWINE_PASSWORD is set to $TWINE_PASSWORD"
        python -m build
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*

  jupyter_test:
    needs: deploy_testpypi
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for deleting the tag
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
    - name: Install Colab-like environment
      run: |
        pip install --index-url https://test.pypi.org/simple/ \
                   --extra-index-url https://pypi.org/simple \
                   starfish-core
        pip install ipython==8.10.0 \
                    ipykernel==6.22.0 \
                    jupyter_http_over_ws>=0.0.8 \
                    pandas==1.5.3 \
                    numpy==1.23.5 \
                    jupyter \
                    pytest \
                    nbval
    - name: Configure Colab simulation
      run: |
        jupyter serverextension enable --py jupyter_http_over_ws
    - name: Run Colab-style tests
      run: |
        pytest --nbval \
          --nbval-kernel-name=python3 \
          --nbval-cell-timeout=120 \
          --nbval-sanitize-with ./tests/sanitize.cfg \
          tests/data_factory/factory/test_resume_index.ipynb

    # Add tag deletion step
    - name: Delete triggering tag after successful test
      if: success() && startsWith(github.ref, 'refs/tags/test-v')
      run: |
        gh api -X DELETE /repos/$GITHUB_REPOSITORY/git/refs/tags/${GITHUB_REF#refs/tags/}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}